service: aws-node-http-api-project

provider:
  name: aws
  runtime: nodejs22.x
  region: ap-northeast-1
  stage: ${opt:stage, 'dev'} # 讓 provider 的 stage 可以從指令中傳入

functions:
  getUsers:
    handler: users.get
    environment:
      DYNAMODB_ENDPOINT: ${self:custom.config.DYNAMODB_ENDPOINT}
    events:
      - httpApi:
          path: /users
          method: get
  addUser:
    handler: users.addUser
    environment:
      DYNAMODB_ENDPOINT: ${self:custom.config.DYNAMODB_ENDPOINT}
    events:
      - httpApi:
          path: /users
          method: post

plugins: ${self:custom.config.plugins}

custom:
  config: ${file(config.${opt:stage, 'dev'}.yml)}
  dynamodb: ${self:custom.config.DYNAMODB_CONFIG}

resources: ${file(resources.yml)}